// Dev mode --vscode-* CSS variable maps for the Vite dev view.

export interface VarMap {
  [cssVar: string]: string;
}

// Dark palette
export const DARK_VARS: VarMap = {
  "--vscode-editor-background": "#1e1e1e",
  "--vscode-editor-foreground": "#cccccc",
  "--vscode-sideBar-background": "#252526",
  "--vscode-sideBar-foreground": "#cccccc",
  "--vscode-panel-background": "#1e1e1e",
  "--vscode-panel-border": "#3c3c3c",
  "--vscode-button-background": "#0e639c",
  "--vscode-button-foreground": "#ffffff",
  "--vscode-button-hoverBackground": "#1177bb",
  "--vscode-button-secondaryBackground": "#3a3d41",
  "--vscode-button-secondaryForeground": "#ffffff",
  "--vscode-button-secondaryHoverBackground": "#45494e",
  "--vscode-input-background": "#3c3c3c",
  "--vscode-input-foreground": "#cccccc",
  "--vscode-input-border": "#3c3c3c",
  "--vscode-input-placeholderForeground": "#a6a6a6",
  "--vscode-dropdown-background": "#3c3c3c",
  "--vscode-dropdown-foreground": "#f0f0f0",
  "--vscode-dropdown-border": "#3c3c3c",
  "--vscode-focusBorder": "#007fd4",
  "--vscode-foreground": "#cccccc",
  "--vscode-descriptionForeground": "#9d9d9d",
  "--vscode-errorForeground": "#f48771",
  "--vscode-icon-foreground": "#c5c5c5",
  "--vscode-list-hoverBackground": "#2a2d2e",
  "--vscode-list-activeSelectionBackground": "#094771",
  "--vscode-list-activeSelectionForeground": "#ffffff",
  "--vscode-list-inactiveSelectionBackground": "#37373d",
  "--vscode-list-inactiveSelectionForeground": "#cccccc",
  "--vscode-badge-background": "#4d4d4d",
  "--vscode-badge-foreground": "#ffffff",
  "--vscode-scrollbarSlider-background": "rgba(121, 121, 121, 0.4)",
  "--vscode-scrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
  "--vscode-scrollbarSlider-activeBackground": "rgba(191, 191, 191, 0.4)",
  "--vscode-statusBar-background": "#007acc",
  "--vscode-statusBar-foreground": "#ffffff",
  "--vscode-tab-activeBackground": "#1e1e1e",
  "--vscode-tab-activeForeground": "#ffffff",
  "--vscode-tab-inactiveBackground": "#2d2d2d",
  "--vscode-tab-inactiveForeground": "#ffffff80",
  "--vscode-tab-activeBorderTop": "#007fd4",
  "--vscode-tab-hoverBackground": "#2a2d2e",
  "--vscode-textLink-foreground": "#3794ff",
  "--vscode-textLink-activeForeground": "#3794ff",
  "--vscode-textCodeBlock-background": "#2d2d2d",
  "--vscode-settings-textInputBackground": "#292929",
  "--vscode-settings-textInputForeground": "#cccccc",
  "--vscode-settings-textInputBorder": "transparent",
  "--vscode-notifications-background": "#252526",
  "--vscode-notifications-foreground": "#cccccc",
  "--vscode-notifications-border": "#3c3c3c",
  "--vscode-disabledForeground": "#6a6a6a",
  "--vscode-checkbox-border": "#c5c5c5",
  "--vscode-editorWidget-background": "#252526",
  "--vscode-editorWidget-foreground": "#cccccc",
  "--vscode-editorWidget-border": "#3c3c3c",
  "--vscode-widget-shadow": "rgba(0, 0, 0, 0.36)",
  "--vscode-menu-background": "#3c3c3c",
  "--vscode-menu-foreground": "#f0f0f0",
  "--vscode-menu-border": "#3c3c3c",
  "--vscode-menu-selectionBackground": "#094771",
  "--vscode-menu-selectionForeground": "#ffffff",
  "--vscode-inputValidation-errorBackground": "#5a1d1d",
  "--vscode-inputValidation-errorBorder": "#be1100",
  "--vscode-inputValidation-errorForeground": "#ffffff",
  "--vscode-inputValidation-warningBackground": "#352a05",
  "--vscode-inputValidation-warningBorder": "#9d8600",
  "--vscode-inputValidation-warningForeground": "#000000",
  "--vscode-inputValidation-infoBackground": "#063b49",
  "--vscode-inputValidation-infoBorder": "#007acc",
  "--vscode-inputValidation-infoForeground": "#ffffff",
  "--vscode-editorError-foreground": "#f48771",
  "--vscode-editorWarning-foreground": "#cca700",
  "--vscode-editorInfo-foreground": "#3794ff",
  "--vscode-charts-yellow": "#cca700",
  "--vscode-testing-iconPassed": "#73c991",
  "--vscode-charts-green": "#4ec9b0",
  "--vscode-progressBar-background": "#0e70c0",
  "--vscode-font-family": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  "--vscode-font-size": "13px",
};

// Light palette
export const LIGHT_VARS: VarMap = {
  "--vscode-editor-background": "#ffffff",
  "--vscode-editor-foreground": "#333333",
  "--vscode-sideBar-background": "#f3f3f3",
  "--vscode-sideBar-foreground": "#333333",
  "--vscode-panel-background": "#ffffff",
  "--vscode-panel-border": "#e7e7e7",
  "--vscode-button-background": "#007acc",
  "--vscode-button-foreground": "#ffffff",
  "--vscode-button-hoverBackground": "#0062a3",
  "--vscode-button-secondaryBackground": "#5f6a79",
  "--vscode-button-secondaryForeground": "#ffffff",
  "--vscode-button-secondaryHoverBackground": "#4c5561",
  "--vscode-input-background": "#ffffff",
  "--vscode-input-foreground": "#333333",
  "--vscode-input-border": "#cecece",
  "--vscode-input-placeholderForeground": "#767676",
  "--vscode-dropdown-background": "#ffffff",
  "--vscode-dropdown-foreground": "#333333",
  "--vscode-dropdown-border": "#cecece",
  "--vscode-focusBorder": "#0090f1",
  "--vscode-foreground": "#333333",
  "--vscode-descriptionForeground": "#717171",
  "--vscode-errorForeground": "#a1260d",
  "--vscode-icon-foreground": "#424242",
  "--vscode-list-hoverBackground": "#e8e8e8",
  "--vscode-list-activeSelectionBackground": "#0060c0",
  "--vscode-list-activeSelectionForeground": "#ffffff",
  "--vscode-list-inactiveSelectionBackground": "#e5ebf1",
  "--vscode-list-inactiveSelectionForeground": "#333333",
  "--vscode-badge-background": "#c4c4c4",
  "--vscode-badge-foreground": "#333333",
  "--vscode-scrollbarSlider-background": "rgba(100, 100, 100, 0.4)",
  "--vscode-scrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
  "--vscode-scrollbarSlider-activeBackground": "rgba(0, 0, 0, 0.6)",
  "--vscode-statusBar-background": "#007acc",
  "--vscode-statusBar-foreground": "#ffffff",
  "--vscode-tab-activeBackground": "#ffffff",
  "--vscode-tab-activeForeground": "#333333",
  "--vscode-tab-inactiveBackground": "#ececec",
  "--vscode-tab-inactiveForeground": "#33333380",
  "--vscode-tab-activeBorderTop": "#0090f1",
  "--vscode-tab-hoverBackground": "#e8e8e8",
  "--vscode-textLink-foreground": "#006ab1",
  "--vscode-textLink-activeForeground": "#006ab1",
  "--vscode-textCodeBlock-background": "#f3f3f3",
  "--vscode-settings-textInputBackground": "#ffffff",
  "--vscode-settings-textInputForeground": "#333333",
  "--vscode-settings-textInputBorder": "#cecece",
  "--vscode-notifications-background": "#f3f3f3",
  "--vscode-notifications-foreground": "#333333",
  "--vscode-notifications-border": "#e7e7e7",
  "--vscode-disabledForeground": "#999999",
  "--vscode-checkbox-border": "#424242",
  "--vscode-editorWidget-background": "#f3f3f3",
  "--vscode-editorWidget-foreground": "#333333",
  "--vscode-editorWidget-border": "#cecece",
  "--vscode-widget-shadow": "rgba(0, 0, 0, 0.16)",
  "--vscode-menu-background": "#ffffff",
  "--vscode-menu-foreground": "#333333",
  "--vscode-menu-border": "#cecece",
  "--vscode-menu-selectionBackground": "#0060c0",
  "--vscode-menu-selectionForeground": "#ffffff",
  "--vscode-inputValidation-errorBackground": "#fce4e4",
  "--vscode-inputValidation-errorBorder": "#be1100",
  "--vscode-inputValidation-errorForeground": "#333333",
  "--vscode-inputValidation-warningBackground": "#fefce4",
  "--vscode-inputValidation-warningBorder": "#9d8600",
  "--vscode-inputValidation-warningForeground": "#333333",
  "--vscode-inputValidation-infoBackground": "#e6f3fb",
  "--vscode-inputValidation-infoBorder": "#007acc",
  "--vscode-inputValidation-infoForeground": "#333333",
  "--vscode-editorError-foreground": "#a1260d",
  "--vscode-editorWarning-foreground": "#bf8803",
  "--vscode-editorInfo-foreground": "#1a85ff",
  "--vscode-charts-yellow": "#bf8803",
  "--vscode-testing-iconPassed": "#388a34",
  "--vscode-charts-green": "#16825d",
  "--vscode-progressBar-background": "#007acc",
  "--vscode-font-family": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  "--vscode-font-size": "13px",
};

// Apply CSS variable map as inline styles on <html> for dev mode.
export function applyDevVars(mode: "light" | "dark"): void {
  const vars = mode === "light" ? LIGHT_VARS : DARK_VARS;
  const root = document.documentElement;
  for (const [key, value] of Object.entries(vars)) {
    root.style.setProperty(key, value);
  }
}
