/* global describe, it */
import { expect } from "chai";

import {
  areTopologyContentsEquivalent,
  computeDeployedTopologyDirtyState,
  type DirtyStateFileSystem
} from "../../../src/reactTopoViewer/extension/services/DirtyState";

class MemoryDirtyStateFs implements DirtyStateFileSystem {
  private readonly files = new Map<string, { content: string; mtimeMs: number }>();

  setFile(filePath: string, content: string, mtimeMs: number): void {
    this.files.set(filePath, { content, mtimeMs });
  }

  statSync(filePath: string): { mtimeMs: number } {
    const file = this.files.get(filePath);
    if (!file) {
      throw new Error(`ENOENT: no such file or directory, stat '${filePath}'`);
    }
    return { mtimeMs: file.mtimeMs };
  }

  readFileSync(filePath: string, _encoding: BufferEncoding): string {
    const file = this.files.get(filePath);
    if (!file) {
      throw new Error(`ENOENT: no such file or directory, open '${filePath}'`);
    }
    return file.content;
  }
}

const YAML_PATH = "/labs/reconcile.clab.yml";
const STATE_PATH = "/labs/clab-reconcile/.state.clab.yaml";

const RECONCILE_TOPOLOGY = `name: reconcile

topology:
  nodes:
    l1:
      kind: nokia_srlinux
      image: ghcr.io/nokia/srlinux
      startup-config: test-l1-startup.cli
    l3:
      kind: linux
      image: alpine:3
      cmd: tail -f /dev/null
      exec:
        - ip address add
    client1:
      kind: linux
      image: ghcr.io/srl-labs/network-multitool:latest
  links:
    - endpoints: [ "l1:e1-2", "l3:eth1" ]
    - endpoints: [ "client1:eth1", "l1:e1-1" ]
`;

const RECONCILE_STATE = `# generated by containerlab at 2026-07-05T16:46:25+02:00
topology:
  defaults: {}
  nodes:
    client1:
      kind: linux
      image: ghcr.io/srl-labs/network-multitool:latest
    l1:
      kind: nokia_srlinux
      startup-config: test-l1-startup.cli
      image: ghcr.io/nokia/srlinux
    l3:
      kind: linux
      image: alpine:3
      cmd: tail -f /dev/null
      exec:
      - ip address add
  links:
  - type: veth
    mtu: 9500
    endpoints:
    - node: l1
      interface: e1-2
    - node: l3
      interface: eth1
  - type: veth
    mtu: 9500
    endpoints:
    - node: client1
      interface: eth1
    - node: l1
      interface: e1-1
`;

describe("topology dirty state", () => {
  it("treats containerlab generated state as equivalent to the source topology", () => {
    expect(
      areTopologyContentsEquivalent(RECONCILE_TOPOLOGY, RECONCILE_STATE, "reconcile")
    ).to.equal(true);
  });

  it("does not mark dirty when mtime is stale but topology content is equivalent", () => {
    const fs = new MemoryDirtyStateFs();
    fs.setFile(YAML_PATH, RECONCILE_TOPOLOGY, 200);
    fs.setFile(STATE_PATH, RECONCILE_STATE, 100);

    expect(computeDeployedTopologyDirtyState(YAML_PATH, "reconcile", fs)).to.equal(false);
  });

  it("marks dirty when the newer topology differs from the state file", () => {
    const fs = new MemoryDirtyStateFs();
    fs.setFile(YAML_PATH, RECONCILE_TOPOLOGY.replace("image: alpine:3", "image: alpine:3.20"), 200);
    fs.setFile(STATE_PATH, RECONCILE_STATE, 100);

    expect(computeDeployedTopologyDirtyState(YAML_PATH, "reconcile", fs)).to.equal(true);
  });

  it("uses mtimes as a cheap clean fast path", () => {
    const fs = new MemoryDirtyStateFs();
    fs.setFile(YAML_PATH, RECONCILE_TOPOLOGY.replace("image: alpine:3", "image: alpine:3.20"), 100);
    fs.setFile(STATE_PATH, RECONCILE_STATE, 200);

    expect(computeDeployedTopologyDirtyState(YAML_PATH, "reconcile", fs)).to.equal(false);
  });

  it("returns unknown when the state file is unavailable", () => {
    const fs = new MemoryDirtyStateFs();
    fs.setFile(YAML_PATH, RECONCILE_TOPOLOGY, 200);

    expect(computeDeployedTopologyDirtyState(YAML_PATH, "reconcile", fs)).to.equal(undefined);
  });
});
